---
knit: "bookdown::render_book"
title: "Introduction to DataCamp"
author: "Tran Thanh Dat"
site: bookdown::bookdown_site
documentclass: book
---

# Welcome to DataCamp {.unnumbered}

<p class="css-1vu6dx7-AboutPage">

Companies and teams of every size use DataCamp to close their data skill gaps and make better data-driven decisions.

</p>

<p class="css-1q65mca">

Data science and analytics are rapidly shaping every aspect of our lives and our businesses.
We're collecting more data than ever before, but not everyone is able to efficiently analyze all that data to extract meaningful insights.
There is incredible power in data---but only if you know what to do with it.
DataCamp teaches companies and individuals the skills they need to work with data in the real world.

</p>

<p class="css-1neit4n-Testimonial">

Data is the core of a business today.
Yet most companies only analyze a fraction of their data, and do so inefficiently.
Many relegate data science knowledge to a small group within the company.
Consequently, they face an enormous skill gap that they can't hire their way out of.
This runs counter to the data transformation initiatives that most companies are going through today.
Democratizing data skills and making entire organizations data fluent is where we come in.

</p>

## Acknowledgements {.unnumbered}

My name is Dat.
I'm a senior student at International University who's been in love with DataCamp ever since I was a sophomore.

I came across this the online learning platform for the sake of passing the Statistics course with flying colors.
My wish came true but something in me just said that DataCamp was much more than Statistics, It focused on building the best learning experience specifically for Data Science.

Now that I am about to graduate, I accumulate all of the important courses learned so far into this website and hope that it would do wonders for the younger especially for those who are pursuing for a professional data career from the very beginning.

For any discussion, please leave a message via dattran.hcmiu\@gmail.com and I will try my best to reply as soon as I can possibly do.
